Valor controllers fix
Valor6800/FRC-6800-2023-code pull request #1
Opened 2022-10-18 14:30 UTC by AntarcticaByToto

-set limits -> add function to set forward and reverse independently
-change PIDF slot on neo
-implemented getCurrent() function

2022-10-19 21:41 UTC, janhelgeson reviewed
@AntarcticaByToto @mray190  Wouldn't we want the ability to enable and DISABLE the limits? It looks like if we wanted to dynamically turn on/off the limits, we cannot. ATM you can only enable the limit

2022-10-19 21:41 UTC, janhelgeson commented on src/main/cpp/controllers/ValorFalconController.cpp
> +void ValorFalconController::setReverseLimit(int reverse)
Any reason not to make this setReverseLimit(int reverse, bool enabled)?

2022-10-19 21:41 UTC, janhelgeson submitted a review, later dismissed
LGTM

2022-10-19 21:45 UTC, janhelgeson reviewed
LGTM

2022-10-19 22:19 UTC, janhelgeson commented on src/main/cpp/controllers/ValorFalconController.cpp
> +void ValorFalconController::setReverseLimit(int reverse)
Turning off limits are not needed. This is a 1 time-config item

2022-10-25 19:53 UTC, mray190 requested changes

2022-10-25 19:53 UTC, mray190 commented on .wpilib/wpilib_preferences.json
> +    "teamNumber": 6803
Change back to 6800

2022-10-25 19:53 UTC, mray190 commented on src/main/cpp/Robot.cpp
> +Robot::Robot() /*: drivetrain(this),*/
Need to re-enable the drivetrain

2022-11-02 21:30 UTC, mray190 approved these changes

2022-11-02 21:30 UTC, merged